Adds documentation on cluster shutdown and startup
SUSE/doc-caasp pull request #1003
Opened 2020-09-23 12:26 UTC by chentex

# Describe your changes
Describe how to shut down a cluster properly
How to start a cluster back up with all intended workloads

For example for moving machines to a different datacenter, migrating to other machines, in preparation for a maintenance window or emergency, startup after an emergency and so on

# Related Issues / Projects
Please provide links to Bugzilla and other GitHub projects with your description if they are related to the changes.

Relates to:
fixes #329

2020-09-23 12:27 UTC, chentex commented on adoc/admin-shutdown-startup.adoc
> +- Take a link:{docurl}/single-html/caasp-admin/#_backup[backup]
I don;t know if this link works completely @r0ckarong if you can confirm.

2020-09-23 13:01 UTC, r0ckarong commented
@chentex Could you please add the respective commands and considerations for each step? 

E.g.:

"Scale applications down to zero"
Which commands do you run, how do you find out it works, how do you check the status, what is the status when you are done?

"Wait for them to come online and are on a healthy status."
What would you run to check on this, how long would you expect this to take, what can you do to troubleshoot if this doesn't happen?

Write as if you're explaining this to someone who has never done this before (like me).

2020-09-23 13:45 UTC, r0ckarong requested changes
@chentex Could you please add the respective commands and considerations for each step?

E.g.:

"Scale applications down to zero"
Which commands do you run, how do you find out it works, how do you check the status, what is the status when you are done?

"Wait for them to come online and are on a healthy status."
What would you run to check on this, how long would you expect this to take, what can you do to troubleshoot if this doesn't happen?

Write as if you're explaining this to someone who has never done this before (like me).

2020-09-25 16:24 UTC, chentex commented
Done updating @r0ckarong

2020-10-12 15:31 UTC, r0ckarong approved these changes

2020-10-12 15:32 UTC, r0ckarong commented
@chentex Could you have another look please. Did formatting and wording review. Added some warnings. If you approve I can merge this.

2020-10-14 07:36 UTC, chentex commented
I see no problems with the modifications, This is good to go.

2020-10-14 07:43 UTC, merged