Backport Helm 3 documentation from 4.5 to 4.2 (#1020)
SUSE/doc-caasp pull request #1027
Opened 2020-10-07 22:12 UTC by jodavis-suse

To support the backport of helm3 (and the update-alternatives
packaging features to the "helm" Helm 2 package), this commit
copies the relevant text back to the CaaS4 branch.

# Describe your changes
What is this PR about? Please briefly detail why this needs to be integrated
and where you think it should go if it's not obvious from the changes.

# Related Issues / Projects
Please provide links to Bugzilla and other GitHub projects with your description if they are related to the changes.

Relates to:

2020-10-09 16:16 UTC, jodavis-suse commented
These documentation changes are required when SUSE/avant-garde#1949 merges.

2020-10-20 09:18 UTC, r0ckarong requested changes
Some minor fixes, rest looks good so far.

2020-10-20 18:25 UTC, jodavis-suse commented on adoc/admin-software-installation.adoc
> +As of {productname} {productversion}, Helm is part of the {productname} package repository, so to use this,
We introduced it in CaaSP 4.5.0, but here we are introducing it to the 4.2.x branch at 4.2.4 as a backport.  So you are right that we should lock in the version here.

2020-10-21 11:52 UTC, r0ckarong commented
Manually picked to `update-424` branch.

2020-10-21 11:52 UTC, closed without merging