Gpu cherry picks
SUSE/doc-caasp pull request #997
Opened 2020-09-16 14:33 UTC by Klaven

These are cherry picks from what we did for 4.5 as we will start supporting 4.2 in CaaSP in the next few weeks. 

Should not get merged until we do another 4.2 release. I think 4.2.3. Anyhow. 

I made this to the `4.2.0 branch as I did not see a 4.2.2 branch. If there is a better place to put these please let me know and I will do that.

# Describe your changes
What is this PR about? Please briefly detail why this needs to be integrated
and where you think it should go if it's not obvious from the changes.

# Related Issues / Projects
Please provide links to Bugzilla and other GitHub projects with your description if they are related to the changes.

Relates to:

2020-09-16 21:33 UTC, cmurphy requested changes
There seem to be a lot of changes unrelated to the topic "Gpu cherry picks", are these necessary for this PR? Could they be split out?

2020-09-22 14:47 UTC, Klaven commented on adoc/admin-gpus.adoc
> +The link:{kubedoc}reference/access-authn-authz/admission-controllers/#extendedresourcetoleration[ExtendedResourceToleration admission controller] is enabled on {productname} v5 by default. This is a
@cmurphy I was going to write something about taints and tolerations today. Not a full overview but just a quick (make sure to remember) Thanks for looking over this and catching these things!

2020-09-22 14:49 UTC, Klaven commented
rebased too the right branch. will make a new commit with my updates too the documentation to reflect the differences in v4.2

2020-09-22 15:37 UTC, cmurphy commented on adoc/admin-gpus.adoc
> +The link:{kubedoc}reference/access-authn-authz/admission-controllers/#extendedresourcetoleration[ExtendedResourceToleration admission controller] is enabled on {productname} v5 by default. This is a
I don't really think anything needs to be written? Just 363075d needs to be removed.

2020-09-30 15:51 UTC, cmurphy commented
It seems like instead of removing the commit I was talking about it got squashed into dcd2a8c0369765e4773315dc39361e4bfe199f02 ? and then undone in 7803b050641d34d91c3defa1c41a52971af3ece9 ? So it's not a true "cherry pick" series but the content looks good to me now :+1:

2020-10-01 17:15 UTC, Klaven commented
@nkoranova do you mind if the history is not a "pure cherry pick"? if it's not a big deal we can merge this. Just let me know and I'll redo it if you want me too.

2020-10-01 17:26 UTC, Klaven commented
@r0ckarong same question too you?

2020-10-01 18:25 UTC, tdaines42 reviewed
The content lgtm. I'm guessing since this is a backport that the formatting issues the CI is calling out is ok? As long as the Docs team is good with it I am

2020-10-05 16:51 UTC, cmurphy commented
I went ahead and fixed the cherry-picks since it bothered me.

2020-10-05 16:54 UTC, Klaven reviewed
@cmurphy cleaned up the history as it should be, thank you. This looks good now.

2020-11-03 09:28 UTC, r0ckarong commented
@davidcassany Is this going to be part of the 4.2.4 release?

2020-12-07 12:34 UTC, r0ckarong commented
CaaSP is in maintenance and only hi-prio security fixes are going to be added.

2020-12-07 12:34 UTC, closed without merging